### ISSUE TITLE
是否有考虑加入其它分支的音源更新

### ISSUE THREAD

**Issue by Masterain98** [nining377/UnblockMusicPro_Xposed#100]
https://github.com/1715173329/UnblockNeteaseMusic

这个Fork目前有人维护，昨天已经增加了更多的音源

**Comment by nining377** [comment]
> https://github.com/1715173329/UnblockNeteaseMusic
> 
> 这个Fork目前有人维护，昨天已经增加了更多的音源

3.0.0已支持手动填入音源
