### ISSUE TITLE
大佬请问一下怎么换自己的服务器啊？

### ISSUE THREAD

**Issue by onewhitethreee** [nining377/UnblockMusicPro_Xposed#102]

**Comment by onewhitethreee** [comment]
> _No description provided._

我自己搞了个服务器想用这个模块连上去，但是找不到哪里能换ip，想问一下

**Comment by nining377** [comment]
> > _No description provided._
> 
> 我自己搞了个服务器想用这个模块连上去，但是找不到哪里能换ip，想问一下

换不了，可以尝试PAC，但是具体怎么弄自己百度吧
