### ISSUE TITLE
59.111.21.13此地址无法连接

### ISSUE THREAD

**Issue by iamwangz** [nining377/UnblockMusicPro_Xposed#11]
04:06:54.645 E/Xposed  ( 7738): 	at bin.xposed.Unblock163MusicClient.HookerDispatcherSelf.dispatch(Unknown Source:24)
09-26 04:06:54.645 E/Xposed  ( 7738): 	... 18 more
09-26 04:08:12.009 I/Xposed  (11336): { Error: connect ECONNREFUSED 59.111.21.13:443
09-26 04:08:12.010 I/Xposed  (11336):     at Object.exports._errnoException (util.js:1026:11)
09-26 04:08:12.010 I/Xposed  (11336):     at exports._exceptionWithHostPort (util.js:1049:20)
09-26 04:08:12.010 I/Xposed  (11336):     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
09-26 04:08:12.010 I/Xposed  (11336):   code: 'ECONNREFUSED',
09-26 04:08:12.010 I/Xposed  (11336):   errno: 'ECONNREFUSED',
09-26 04:08:12.010 I/Xposed  (11336):   syscall: 'connect',
09-26 04:08:12.010 I/Xposed  (11336):   address: '59.111.21.13',
09-26 04:08:12.010 I/Xposed  (11336):   port: 443 }
09-26 04:09:14.889 I/Xposed  (12882): { Error: connect ECONNREFUSED 59.111.21.13:443
09-26 04:09:14.889 I/Xposed  (12882):     at Object.exports._errnoException (util.js:1026:11)
09-26 04:09:14.889 I/Xposed  (12882):     at exports._exceptionWithHostPort (util.js:1049:20)
09-26 04:09:14.889 I/Xposed  (12882):     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
09-26 04:09:14.889 I/Xposed  (12882):   code: 'ECONNREFUSED',
09-26 04:09:14.889 I/Xposed  (12882):   errno: 'ECONNREFUSED',
09-26 04:09:14.889 I/Xposed  (12882):   syscall: 'connect',
09-26 04:09:14.889 I/Xposed  (12882):   address: '59.111.21.13',
09-26 04:09:14.889 I/Xposed  (12882):   port: 443 }

**Comment by nining377** [comment]
把除了第一个开关之外的都关了，然后重启一下一般就能解决了，原因为部分机型nodejs后台未随着网易云的退出而关闭导致，而UnblockMusic Pro并没有足够的权限关闭它

**Comment by nining377** [comment]
请更新0.19.4版本的脚本
