### ISSUE TITLE
啟動網易雲音樂後，依序提示"網路異常"、"加載失敗"、"運行失敗"

### ISSUE THREAD

**Issue by rti56kt** [nining377/UnblockMusicPro_Xposed#13]
網易雲音樂版本：6.1.1
Android版本：9.0
Xposed環境：使用太極陽(太極Magisk)

所有音源優先級都試過了一遍
也試過只留"啟用模塊"其他通通取消勾選
但網易雲音樂啟動後不斷提示：
1. "網路異常"
2. "加載失敗，請點擊重試。code：2，error：conn"
3. "運行失敗，錯誤為：SyntaxError: Unexpected token *"

手機中沒有音量增強器模組，但有使用雲村清潔工、網易雲音樂插件這2個模組
有嘗試過將此2模組禁用，但仍然出現同樣問題
ps. 此問題是最近才發生的，上星期都還能正常運作

**Comment by cc9014** [comment]
网易云音乐版本：6.4.1
Android版本：9.0
Xposed环境：太极阴
启用模块：CoolapkEx, 微X模块, UnblockMusic Pro

仅勾选“启用模块”和"隐藏本模块图标"，音源优先级：酷我

打开网易云音乐提示 “运行失败，错误为：SyntaxError: Unexpected token *”

**Comment by nining377** [comment]
@rti56kt @cc9014 请把内置存储卡目录下的UnblockMusicPro文件夹删除，并清除网易云音乐的数据，这是由于2.6.0版本遗留的问题，新版已修复
