### ISSUE TITLE
太极阴可以用吗？

### ISSUE THREAD

**Issue by 1211798276** [nining377/UnblockMusicPro_Xposed#14]
太极阴可以用吗？我用着出现未知错误，失败

**Comment by cedar-c** [comment]
> 太极阴可以用吗？我用着出现未知错误，失败

好巧，我也是

**Comment by ZogeMung** [comment]
太极阳同样问题，不仅是未知错误，而且网易云连不上网，重新登录的话登陆不了

**Comment by infinity560** [comment]
有没有办法 支援太极阴呢？ 谢谢大大

**Comment by cc9014** [comment]
太极阴可以用啊，我就正常使用中。。

**Comment by 1211798276** [comment]
表示我一会正常一会不正常

**Comment by 1211798276** [comment]
但是我用xp框架就可以完全正常使用

**Comment by David318** [comment]
太极阴可以用，用了一晚上，今天出去了一趟然后就用不了了，现在回家也用不了了，不知道什么问题

**Comment by David318** [comment]
> 太极阴可以用，用了一晚上，今天出去了一趟然后就用不了了，现在回家也用不了了，不知道什么问题

换成太极阳了，目前正常使用，安卓8.0，网易云6.4.3
