### ISSUE TITLE
271版本无法播放网易云视频

### ISSUE THREAD

**Issue by Evinemz** [nining377/UnblockMusicPro_Xposed#17]
网易云的视频在启用模块后无法播放，提示：播放视频失败了，请点击重试

**Comment by nining377** [comment]
请提供网易云版本号，经测试6.0.0与6.4.2版本没有问题

**Comment by gitforho** [comment]
2.7.1搭配网易云4.3.1无法下载歌曲，试了周杰伦和Taylor swift全下载失败

**Comment by Evinemz** [comment]
感谢回复 可能是当天的问题 重新测试已经没问题了
