### ISSUE TITLE
无法下载歌曲

### ISSUE THREAD

**Issue by gitforho** [nining377/UnblockMusicPro_Xposed#19]
2.7.1+太极阴+网易云4.3.1无法下载歌曲，试了周杰伦和Taylor swift全下载失败,下载的过程中有下载进度，只是下载到到最后都会失败

**Comment by nining377** [comment]
谷歌版4.3.1现在不是也有广告了吗，还有啥理由让你停留在4.3.1呢？建议升级到6.0.0配合云村清洁工

**Comment by swh922** [comment]
包比较小吧，我也一直在用，同样下载失败，但是我平常都是在线听歌

**Comment by Mellovo** [comment]
我6.0.0也一样无法下载了，在线可以听

**Comment by caliban511** [comment]
我这边也是，不只是周杰伦和霉霉，很多歌都是能获取、可以开始下载、有过程，最后显示下载失败。。。同样的歌在电脑用网易云软件和脚本版可以正常下载，可见这是这个APP的问题，与原脚本无关。。。很多个版本了，一直是这样，不知道什么时候才能修复。。。。。
