### ISSUE TITLE
请求解决第三方登录问题

### ISSUE THREAD

**Issue by frankyifei** [nining377/UnblockMusicPro_Xposed#29]
在太极阴下面使用，无root权限
微信和微博登录不可用。 点微信提示有签名问题，点微博没有反应。

**Comment by naloder** [comment]
这是因为太极阴要使用插件必须修改APK，动过签名的势必不能第三方登录

**Comment by nining377** [comment]
@naloder 感谢替我回答
@frankyifei 太极阴为了能在不root的情况下实现xposed的功能必须在目标app中植入一段hook入口代码，势必会修改apk并重新签名，这会导致第三方登录及分享验证错误。如需登录请使用手机号，分享则暂时无解
