### ISSUE TITLE
[已解决]关于出现”加载失败，请点击重试 code:2,error:io“

### ISSUE THREAD

**Issue by liuhaofay** [nining377/UnblockMusicPro_Xposed#34]
如题，插件，脚本都是最新的。
网易云音乐最新版提示   

加载失败，请点击重试
code：2，error：io

然后换了6.5.2，还是不行，又换了谷歌最后一版，4.3.1 这次没提示了，但是灰色还是灰色，不能听

**Comment by liuhaofay** [comment]
大佬，0.24脚本更新不了啊，试了几十遍，流量，wifi，梯子都不行，提示更新完了，但是脚本的版本还是没有变，把unblockmusic pro文件夹删了也不行，现在脚本成0.20了，蓝走盘的密码也不对，无法下载

**Comment by a3500976** [comment]
+1  不知道怎么解决

**Comment by a3500976** [comment]
老哥  我发现这和手机有关  软件本身是没问题的  我现在用的索尼x1 9.0的  和你一样用不了  提示找不到什么文件   另一个8.0的htcU11却是正常的 一样的网易云音乐版本和插件版本  可以加个QQ交流一下 384862518

**Comment by liuhaofay** [comment]
大佬能否帮忙看看是什么原因，今天又试了，还是得挂梯子才行。客户端是7.0.20，插件是今天更新的最新版2.7.4，脚本用插件自带的0.24.1，后来把unblockmusicpro文件夹删了，在脚本发布页重新下载了0.24.1的脚本。还是不行。不挂梯子就提示
加载失败，请点击重试
code：2，error：io

**Comment by liuhaofay** [comment]
是不是服务器被墙了？

**Comment by a3500976** [comment]
我不知道。。。我也是小白   我一个手机能正常用  另一个用不了  现在改用大音量了

**Comment by nining377** [comment]
本项目并没有服务器，检查更新依赖于GitHub @liuhaofay @a3500976

**Comment by liuhaofay** [comment]
@nining377  大佬能不能帮忙分析下，电脑上也用的是0.24.1的脚本，能直接用，不用架梯子，但是手机上不架梯子就连不上，MIUI11，magisk20.4，xposed用的是太极magisk，也是最新版。

**Comment by nining377** [comment]
> @nining377 大佬能不能帮忙分析下，电脑上也用的是0.24.1的脚本，能直接用，不用架梯子，但是手机上不架梯子就连不上，MIUI11，magisk20.4，xposed用的是太极magisk，也是最新版。

你可以尝试清除网易云数据并删除位于sdcard根目录下的UnblockMusicPro文件夹

**Comment by liuhaofay** [comment]
> > @ nining377大佬能不能帮忙分析下，电脑上也用的是0.24.1的脚本，能直接用，不用架梯子，但是手机上不架梯子就连不上，MIUI11，magisk20.4，xposed用的是太极magisk，也是最新版。
> 
> 你可以尝试清除网易云数据并删除位于sdcard根目录下的UnblockMusicPro文件夹

这个方法不行，我试过了，清除，也删了，我以为是太极的问题，今天把太极删了，换为EdXposed，还是不行，不挂梯子就提示

加载失败，请点击重试
code：2，error：io

**Comment by liuhaofay** [comment]
昨天晚上捣鼓到夜里1点多，终于找出了问题的所在，我对不起大家，给大家找麻烦了。
如果出现：
加载失败，请点击重试 
code:2,error:io
请检查手机是否用了Hosts去广告或其他Hosts相关服务，问题就能得到解决。
