### ISSUE TITLE
脚本24更新不了

### ISSUE THREAD

**Issue by Howard20181** [nining377/UnblockMusicPro_Xposed#35]
一个奇怪的bug，一直更新一直high
![Screenshot_2020-02-24-09-11-02-901_com raincat unblockmusicpro](https://user-images.githubusercontent.com/40033067/75123951-d426c980-56e6-11ea-8431-78bb4c9fa47c.jpg)

**Comment by elvisw** [comment]
同样的问题

**Comment by liuhaofay** [comment]
+1,能不能把0.23.1的脚本给我发一份？我把硬盘里的unblockmusic pro 文件夹删了，结果现在变成0.20的脚本了。
先谢谢拉！ liuhaofay@163.com

**Comment by elvisw** [comment]
> +1,能不能把0.23.1的脚本给我发一份？我把硬盘里的unblockmusic pro 文件夹删了，结果现在变成0.20的脚本了。
> 先谢谢拉！ [liuhaofay@163.com](mailto:liuhaofay@163.com)

脚本这里下
https://github.com/nondanee/UnblockNeteaseMusic/releases

**Comment by Howard20181** [comment]
版本2.7.4已解决

**Comment by elvisw** [comment]
多谢修复，请作者提交一下太极的模块适配引擎
