### ISSUE TITLE
请问老哥，UnblockMusicPro不支持edxposed吗

### ISSUE THREAD

**Issue by soxio** [nining377/UnblockMusicPro_Xposed#39]
模块已启用，但是歌曲还是显示灰色

**Comment by txyyh** [comment]
没呀，我这边edxposed正常，可以放灰色的歌
magisk版本20.3 edxposed 0.4.5.1
系统mokee 9，手机三星 note 3

**Comment by soxio** [comment]
> 没呀，我这边edxposed正常，可以放灰色的歌
> magisk版本20.3 edxposed 0.4.5.1
> 系统mokee 9，手机三星 note 3

刚才把edxposed换成跟你一样的版本还是显示灰色，网易云版本是6.4.0

**Comment by soxio** [comment]
> 没呀，我这边edxposed正常，可以放灰色的歌
> magisk版本20.3 edxposed 0.4.5.1
> 系统mokee 9，手机三星 note 3

登录了下账号就可以了。。。
