### ISSUE TITLE
太极阳6.0.2 安卓10 网易云6.4 提示 文件完整性校验失败

### ISSUE THREAD

**Issue by tiandawen** [nining377/UnblockMusicPro_Xposed#40]
太极阳6.0.2 安卓10 网易云6.4 提示 文件完整性校验失败。root版在哪下载

**Comment by nining377** [comment]
与重定向冲突，你可以在已关闭的issue中找到答案

**Comment by tiandawen** [comment]
> 与重定向冲突，你可以在已关闭的issue中找到答案

但是我没有做重定向啊 没装过类似的东西

**Comment by nining377** [comment]
已在README中提供蓝奏盘，你可以试试root版了

**Comment by tiandawen** [comment]
> 已在README中提供蓝奏盘，你可以试试root版了

谢谢 root可以使用了

**Comment by nining377** [comment]
好的，记得帮我点小星星
