### ISSUE TITLE
app里的node版本为6.8，可更新

### ISSUE THREAD

**Issue by ActiveIce** [nining377/UnblockMusicPro_Xposed#49]
这里有根据最新源码每日自动编译的node
已经在我的Pixel 3  Android 10 测试通过

https://github.com/ActiveIce/node-android
可以拿来测试一下能不能用

**Comment by nining377** [comment]
太大了，所以最后并未考虑，而且目前6.8并无任何问题

**Comment by ActiveIce** [comment]
行  那我close了
