### ISSUE TITLE
关于与“存储重定向”的兼容问题

### ISSUE THREAD

**Issue by jxLYH6134** [nining377/UnblockMusicPro_Xposed#53]
之前一直报错：”文件完整性校验失败“，后来了解到与存储重定向有关。在重刷好几次后排查到了问题，只要网易云音乐和UnblockMusuc其中一个被“重定向”操作了就会导致这个错误。考虑到本模块工作原理与本地代理有关，就先从应用创建的“UnblockMusicPro”文件夹下手，具体操作为——在隔离后要把UMP的“可访问文件夹”链接到创建的UMP文件夹(等下，那我隔离了个寂寞？？)；此时应用依然报错，因为作为一个Xposed模块，模块应该是可以以生效应用的身份读写的——所以还需要把网易云音乐也允许读写这个文件夹，同上 也要把网易云音乐可访问勾选UMP。此时就可以正常提示“运行成功，当前优先选择……”弹窗啦，而且干掉了不规范的“netease”毒瘤文件夹(笑)
至于这个UnblockMusicPro文件夹……看在区分大小写的份上不算毒瘤嗯😂

**Comment by jxLYH6134** [comment]
补充一下，说Unblock文件夹毒是不对的哈，要是放在模块的私有缓存文件夹，网易云执行容易出问题😄

**Comment by nining377** [comment]
没有办法，代理要做到与网易云音乐同生共死，那宿主只能是网易云音乐，那就只能通过中间文件夹去处理，如果你把文件放到UnblockMusicPro的私有文件夹之后网易云没办法访问到代理。

**Comment by jxLYH6134** [comment]
能用xp版就还是不换root版了。找到的最简解决方法就只要让网易云被隔离后允许读写Unblock文件夹即可，其他都不用。而模块本体并未创造其他文件夹，查证没有隔离的必要，且因为权限和运行的关系此文件夹是必须的。同时会使用重定向和Unblock的用户相想必不少，在问题解答中可以加上一段简单描述或者链接到issue，可以帮助其他用户定位并解决问题

**Comment by nining377** [comment]
嗯，可以考虑添加，感谢反馈

**Comment by NewBugger** [comment]
两个均重定向，并令网易云 sync_folder -> sdCard/Music/Netease

**Comment by nakixii** [comment]
> 两个均重定向，并令网易云 sync_folder -> sdCard/Music/Netease

sync_folder是哪个？

**Comment by muzigui** [comment]
我直接把UnblockMusicPro文件夹 复制到Netease 文件夹里 就ok了

**Comment by BruceZhang1993** [comment]
![Screenshot_20201011-104502](https://user-images.githubusercontent.com/6873988/95669086-18e86d80-0baf-11eb-8d6e-c9c9fbb9d7c0.png)

如果应用和模块都隔离然后添加上面的规则就可以了
如果应用隔离模块不隔离，只要允许网易云访问目录即可

**Comment by eatonmichael** [comment]
> 

哥，图片上是哪个APP，我是小白😭碰到这个重定向问题不知道怎么解决

**Comment by eatonmichael** [comment]
> ![Screenshot_20201011-104502](https://user-images.githubusercontent.com/6873988/95669086-18e86d80-0baf-11eb-8d6e-c9c9fbb9d7c0.png)
> 
> 如果应用和模块都隔离然后添加上面的规则就可以了 如果应用隔离模块不隔离，只要允许网易云访问目录即可

哥，图片上是哪个APP，我是小白😭碰到这个重定向问题不知道怎么解决
