### ISSUE TITLE
无版权音乐匹配错误

### ISSUE THREAD

**Issue by zhanqiuzhang** [nining377/UnblockMusicPro_Xposed#56]
在播放网易无版权的音乐时会匹配到错误的源。比如播放 杨宗纬 的《一次就好》，得到的只有伴奏而没有人声。
希望大佬能够解决~

**Comment by nining377** [comment]
由于是替换音源而不是破解，所以有部分歌曲匹配错误是正常的，可以把高音质支持的勾去掉试试

**Comment by zhanqiuzhang** [comment]
没有勾选高音质

**Comment by nining377** [comment]
> 没有勾选高音质

没有勾选也是音源替换呀，只是网易云本身有的歌曲就替换了而已，如果你这首歌网易云没版权或者付费，那么勾不勾都会去其他地方获取音源
