### ISSUE TITLE
【求助】总有些歌下载不了。。。。。。。

### ISSUE THREAD

**Issue by caliban511** [nining377/UnblockMusicPro_Xposed#57]
大佬你好，绝大多数情况下都是好的，但总有些歌下载不了。
这些在电脑上试过了，使用nondanee大佬的UnblockNeteaseMusic项目在电脑上可以正常下载。
清除过网易云的数据了，删掉过内置存储里的UnblockMusicPro文件夹了，在EDxp里禁用启用重启手机试过了，但貌似不行。
小米MAX3，MIUI 11.0.1稳定版，核心是安卓10
网易云音乐：国内版7.0.20

![photo_2020-05-28_19-33-52](https://user-images.githubusercontent.com/13557387/83136619-62fa1680-a11a-11ea-884b-ffcbd974ce30.jpg)

**Comment by caliban511** [comment]
还有这些提示要VIP的。
![Screenshot_2020-05-29-13-08-18-131_com netease cloudmusic](https://user-images.githubusercontent.com/13557387/83223600-d00abc00-a1ad-11ea-981d-7e2b6681ac90.jpg)

**Comment by nining377** [comment]
可以配合我的另一个项目使用哦

**Comment by caliban511** [comment]
> 可以配合我的另一个项目使用哦

感谢大佬回复，我又用了 UnblockNeteaseMusic 绝大部分的都能下载了，但还是有几个不行，装了杜比大喇叭也是不行，求大佬验证一下。

![Screenshot_2020-05-30-16-02-39-899_com netease cloudmusic](https://user-images.githubusercontent.com/13557387/83323180-9ca05e00-a28f-11ea-978d-c74dc9c0830f.jpg)

**Comment by nining377** [comment]
> > 可以配合我的另一个项目使用哦
> 
> 感谢大佬回复，我又用了 UnblockNeteaseMusic 绝大部分的都能下载了，但还是有几个不行，装了杜比大喇叭也是不行，求大佬验证一下。
> 
> ![Screenshot_2020-05-30-16-02-39-899_com netease cloudmusic](https://user-images.githubusercontent.com/13557387/83323180-9ca05e00-a28f-11ea-978d-c74dc9c0830f.jpg)

下载不了就是彻底没有音源的了，你可以试试能否播放

**Comment by caliban511** [comment]
> 下载不了就是彻底没有音源的了，你可以试试能否播放

哈哈，装上最新版的1.0.2版大喇叭，搞定了！还是大佬你牛逼！( ˘ ³˘)♥

**Comment by nining377** [comment]
嗯呢，那我就把issue关了哦
