### ISSUE TITLE
使用存储重定向后插件提示“文件完整性校验失败”

### ISSUE THREAD

**Issue by NigelSong** [nining377/UnblockMusicPro_Xposed#6]
网易云音乐版本6.1.0，音乐软件和插件都使用了存储重定向。已经在EDXposed里给了XP权限，也给插件和网易云加了白名单，存储权限已经授予了插件。插件现在无法工作，还望开发者尽快解决，谢谢！

**Comment by nining377** [comment]
我不知道重定向的工作原理，不过文件必须在data或者system目录之下才会有可执行权限，而一般在无root的情况下软件只能更改自身data/data/目录下的文件权限，所以一旦你重定向到了别处那么没有可执行权限脚本是运行不起来的，所以该问题唯一解决办法是不使用重定向。

**Comment by NigelSong** [comment]
存储重定向只改变应用在/sdcard里的存储路径，不改变/data路径下的文件路径，所以开发者您看问题是否出在这个存储重定向上？

**Comment by nining377** [comment]
那问题应该不是出在重定向本身，但是曾遇到过使用重定向的人取消重定向后成功执行，你可以把重定向APP的下载链接发来，我有空测试一下

**Comment by NigelSong** [comment]
https://www.coolapk.com/apk/moe.shizuku.redirectstorage
存储重定向APP

**Comment by ExcitedEven** [comment]
加油啊大佬，没了Unblock或者重定向都难受啊

**Comment by nining377** [comment]
@NigelSong @ExcitedEven

**Comment by M0Sheng** [comment]
请问root版在哪里下载呢?

**Comment by llsl666** [comment]
海外用户是不是无法下载歌曲  ，我目前下哪个都是下载失败，海外用户是要跳回国内才能下载吗
