### ISSUE TITLE
下载完成后提示“下载失败”

### ISSUE THREAD

**Issue by UncommonRuler** [nining377/UnblockMusicPro_Xposed#60]
UnblockMusicPro为最新版，网易云音乐版本7.1.71。尝试过使用7.0.10版本的网易云音乐，测试过程中未使用其他网易云音乐相关模块。
具体表现为能获取到音乐资源并下载：
![Screenshot_2020-06-13-03-18-04-378_com netease cloudmusic](https://user-images.githubusercontent.com/21164383/84538969-31da3280-ad25-11ea-8abc-a668361adf19.jpg)
但是完成后立即提示下载失败：
![Screenshot_2020-06-13-03-18-11-518_com netease cloudmusic](https://user-images.githubusercontent.com/21164383/84539037-50d8c480-ad25-11ea-898b-1bd2e9d5aea6.jpg)
日志文件：
[error.log](https://github.com/nining377/UnblockMusicPro_Xposed/files/4772802/error.log)
小星星已献上，希望大佬能抽空帮帮忙。

**Comment by UncommonRuler** [comment]
不用麻烦大佬了，问题已经解决。
之前配合UnblockMusicPro使用的是[网易云音乐插件](https://repo.xposed.info/node/1602)， 已经年久失修。换上大佬的[杜比大喇叭](https://github.com/nining377/dolby_beta)后，问题迎刃而解。
建议单独用UnblockMusicPro出问题的小伙伴配合杜比大喇叭使用。

**Comment by nining377** [comment]
> 不用麻烦大佬了，问题已经解决。
> 之前配合UnblockMusicPro使用的是[网易云音乐插件](https://repo.xposed.info/node/1602)， 已经年久失修。换上大佬的[杜比大喇叭](https://github.com/nining377/dolby_beta)后，问题迎刃而解。
> 建议单独用UnblockMusicPro出问题的小伙伴配合杜比大喇叭使用。

杜比大喇叭使用的是另一种方式绕开了下载校验，而且维护到的版本都比较新，所以最好是大喇叭配合UnblockMusic Pro使用哦
