### ISSUE TITLE
网易云证书与AdGuard证书冲突

### ISSUE THREAD

**Issue by leeyiding** [nining377/UnblockMusicPro_Xposed#64]
当网易云音乐流量经过adguard路由后，unblockmusic Pro的toast报错unable verify the first certificate
adguard的证书已移动至系统证书存储区。

**Comment by nining377** [comment]
emmmmmm...这是node报的错，模块并无办法处理这个错误，也无法给出解决方案

**Comment by nondanee** [comment]
@nining377 你把这个插到代码里好了
```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0
```

**Comment by nining377** [comment]
> @nining377 你把这个插到代码里好了
> 
> ```js
> process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0
> ```

好哒ヾ(Ő∀Ő๑)ﾉ
