### ISSUE TITLE
已经允许读写手机存储，打开网易云音乐仍提示需要授予权限

### ISSUE THREAD

**Issue by JueLuo99** [nining377/UnblockMusicPro_Xposed#7]
已经授予相关权限，打开网易云APP后，弹出 toast 提示“文件完整性检验失败，请打开 UnblockMusic Pro 并同意存储卡访问权限”

**Comment by nining377** [comment]
你打开unblockmusic pro就好了啊，它要释放文件，会自己请求权限的

**Comment by JueLuo99** [comment]
> 你打开unblockmusic pro就好了啊，它要释放文件，会自己请求权限的

打开后没有反应，问题仍然存在
