### ISSUE TITLE
为什么无损不能下载

### ISSUE THREAD

**Issue by wanger123456** [nining377/UnblockMusicPro_Xposed#73]
升级到2.82，酷我音源无版权的可以听，但是下载提示都是失败，请问怎么回事，还需要什么设置吗

**Comment by 980864138** [comment]
同问，请作者有空回答一下

**Comment by pochen448** [comment]
再用一个作者弄的的杜比大喇叭b版，他好象把下载验证去除弄到那里去了，所以没用那个下载不了

**Comment by nining377** [comment]
> 再用一个作者弄的的杜比大喇叭b版，他好象把下载验证去除弄到那里去了，所以没用那个下载不了

嗯嗯，是的，UnblockMusic只解决无版权的问题，其他的不再负责
