### ISSUE TITLE
我遇到了歌曲不变灰，但内容是混乱的

### ISSUE THREAD

**Issue by Dacanid** [nining377/UnblockMusicPro_Xposed#78]
音量增强器 0.0.35
UnblockMusic Pro 2.8.2
云村清洁工 2.7.0

WYYYY版本 V7.2.0.304154

拿Jay Chou的烟花举例，点击歌曲后播放的是其他歌曲，或者是伴奏，音源切换了好几个都是这样

**Comment by nining377** [comment]
模块的功能是音源替换，并不是pojie无版权哦，所以可能有些音乐没有对应音源就会出错，还有请勿让增强器与UnblockMusic Pro同时工作，否则可能会有一个失效，你可以尝试在UnblockMusic Pro中切换不同音源尝试
