### ISSUE TITLE
错误:用户校验失败或授权到期

### ISSUE THREAD

**Issue by raging-flames** [nining377/UnblockMusicPro_Xposed#97]
![1e51def969d0ff5411cacb38a1fa88f8](https://user-images.githubusercontent.com/67429400/109135189-c2f91880-7791-11eb-846b-c1cb1cc26fbc.jpg)

**Comment by nining377** [comment]
请卸载杜比大喇叭后重试

**Comment by swh922** [comment]
@raging-flames 给模块存储空间权限
