### ISSUE TITLE
不能用了，QQ和酷我API有变动

### ISSUE THREAD

**Issue by Yusoo** [nining377/UnblockMusicPro_Xposed#99]
能升个级吗

https://github.com/nondanee/UnblockNeteaseMusic/issues/746

**Comment by eatenupme** [comment]
@Yusoo   

https://github.com/nondanee/UnblockNeteaseMusic/issues/746 

![image](https://user-images.githubusercontent.com/64666574/117093372-543cca80-ad93-11eb-958e-b12a020e7c5c.png)

download掉这个傻瓜式的版本, 替换掉大喇叭的script. 

就我目前来看大部分歌曲是正常的, 有些歌曲非伴奏但不是原声.
